Repository p-zywczak/demo-repository, pull requests merged in 2024-09, with the labels that each got.

#44 permmisionxsxs
  dasdasdas.txt
Labels: Documentation, QA Dev, CR1, CR2

#45 permmisionxsxs
  nksadnlas.txt
Labels: Documentation, QA Dev, CR1, CR2

#46 permmisionxsxs
  kikiki
Labels: Documentation, QA Dev, CR1, CR2

#65 perismsms
  waaaaaa.txt
Labels: Documentation, QA Dev, CR1, CR2

#67 perismsms
  kokok.txt
Labels: Documentation, QA Dev, CR1, CR2

#69 perismsms
  lol.txt
Labels: Documentation, QA Dev, CR1, CR2

#70 perismsms
  csgo.txt
Labels: Documentation, QA Dev, CR1, CR2

#71 perismsms
  musidzialac
Labels: Documentation, QA Dev, CR1, CR2

#78 testlol1
  czydziala.txt
Labels: Documentation, QA Dev, CR1, CR2, Not Documentation

#87 testlol1
  feat.txt
Labels: Documentation, QA Dev, CR1, CR2

#90 testlol1
  qwerty
Labels: Documentation, QA Dev, CR1, CR2

#93 testlol1
  atest.txt
Labels: Documentation, QA Dev, CR1, CR2

#97 testlol1
  bvbvbv.txt
Labels: Documentation, QA Dev, CR1, CR2

#101 testlol1
  hujdgsufdgsufdosf.txt
Labels: Documentation, QA Dev, CR1, CR2

#104 testlol1
  lolek.txt
Labels: Documentation, QA Dev, CR1, CR2

#107 testlol1
  jojoj.txt
Labels: Documentation, QA Dev, CR1, CR2

#110 testlol1
  popo.txt
Labels: Documentation, QA Dev, CR1, CR2

#133 testlol1
  bgfbgfbfg.txt
Labels: Documentation, QA Dev, CR1, CR2

#155 Create dasdasdasdas
  dasdasdasdas
Labels: Do Merge

#211 TEST-232
  vecdvcdvcd
Labels: QA Dev, CR1, CR2, Not Documentation

#213 Create ncvnewww
  ncvnewww
Labels: QA Dev, CR1, CR2, Not Documentation

#223 Create vdvdvd
  vdvdvd
Labels: Do Merge

#225 Create bfbew
  bfbew
Labels: Do Merge

#227 Create bgfbfgb1321
  bgfbfgb1321
Labels: Do Merge
